# Project information
site_name: 'Computer Science Notes'
site_description: 'Computer Science Notes Operating System LeetCode Python Machine Learning'
site_author: 'Jay Chen'
site_url: 'https://walkccc.github.io/CS'

# Repository
repo_name: 'walkccc/CS'
repo_url: 'https://github.com/walkccc/CS'

# Copyright
copyright: 'Built by <a href="http://github.com/walkccc">Jay Chen</a> &copy; 2017 - 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  favicon: 'assets/favicon.png'
  palette:
    primary: 'Indigo'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'important_devices'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/walkccc'
    - type: 'book'
      link: 'https://walkccc.github.io/CLRS'
    - type: 'gamepad'
      link: 'https://walkccc.github.io/webapps'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jay-chen-57852313a'
    - type: 'instagram'
      link: 'https://www.instagram.com/walkccc'
    
extra_css:
  - 'css/style.css'

extra_javascript:
  - 'js/mathjax.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Preface: index.md
  - LeetCode in Python: 
    - Preface: LeetCode/index.md
    - 001-100:
      - 001-010: LeetCode/001-100/001-010.md
      - 011-020: LeetCode/001-100/011-020.md
      - 021-030: LeetCode/001-100/021-030.md
      - 031-040: LeetCode/001-100/031-040.md
      - 041-050: LeetCode/001-100/041-050.md
  - Operating System:
    - Preface: OS/index.md
    - PART ONE | OVERVIEW:
      - Chapter 1 Introduction: OS/Chap01.md
      - Chapter 2 Operating-System Structures: OS/Chap02.md
    - PART TWO | PROCESS MANAGEMENT:
      - Chapter 3 Processes: OS/Chap03.md
      - Chapter 4 Threads: OS/Chap04.md
      - Chapter 5 Process Synchronization: OS/Chap05.md
      - Chapter 6 CPU Scheduling: OS/Chap06.md
      - Chapter 7 Deadlocks: OS/Chap07.md
    - PART THREE | MEMORY MANAGEMENT:
      - Chapter 8 Main Memory: OS/Chap08.md
      - Chapter 9 Virtual Memory: OS/Chap09.md
    - Previous Exams: 
      - Midterm: OS/midterm.md
      - Final: OS/final.md
  - Machine Learning:
    - Preface: ML/index.md
    - Regression - Case Study: ML/1.md
    - Where does the error com from?: ML/2.md