# Project information
site_name: 'Operating System | notes'
site_description: 'Notes of Operating System'
site_author: 'Jay Chen'
site_url: 'https://walkccc.github.io/OSnotes'

# Repository
repo_name: 'walkccc/OSnotes'
repo_url: 'https://github.com/walkccc/OSnotes'

# Copyright
copyright: 'Copyright &copy; 2018 Jay Chen'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Light Blue'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/walkccc'
    - type: 'book'
      link: 'https://walkccc.github.io/CLRS'
    - type: 'gamepad'
      link: 'https://walkccc.github.io/MemoryGame'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jay-chen-57852313a'
    - type: 'instagram'
      link: 'https://www.instagram.com/walkccc'
    
extra_css:
  - 'css/style.css'

extra_javascript:
  - 'javascripts/mathjax.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

pages:
  - Preface: index.md
  - PART ONE | OVERVIEW:
    - Chapter 1 Introduction: Ch01.md
    - Chapter 2 Operating-System Structures: Ch02.md
  - PART TWO | PROCESS MANAGEMENT:
    - Chapter 3 Processes: Ch03.md